"""empty message

Revision ID: 0aae220062db
Revises: b39c0a26b633
Create Date: 2021-07-07 14:34:24.979173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aae220062db'
down_revision = 'b39c0a26b633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairings', sa.Column('backdrop_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairings', 'backdrop_path')
    # ### end Alembic commands ###
